buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext{
    minSdkSersion = 19
    compileSdkVersion = 34
    targetSdkVersion = 34
    versionCode = 1
    versionName = "1.0"
}
