pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

rootProject.name = 'MyCloudMusicAndroidJava'
includeBuild('../mycloudmusic-common-utils') {
    dependencySubstitution {
        substitute module('com.mycloudmusic:common-utils') using project(':')
    }
}
include ':app'
